# Generated by Django 4.0.3 on 2022-05-24 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_userprofile_bio_userprofile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_thread_first', to='account.userprofile')),
                ('second', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_thread_second', to='account.userprofile')),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('snap', models.ImageField(blank=True, null=True, upload_to='chat_images')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('mythread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.mythread')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.userprofile', verbose_name='sender')),
            ],
        ),
    ]
