# Generated by Django 4.0.3 on 2022-05-25 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chatmessage_mythread'),
    ]

    operations = [
        migrations.AddField(
            model_name='mythread',
            name='latest_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lm', to='chat.chatmessage'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='mythread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.mythread'),
        ),
    ]
